server:
  # HTTP端口
  port: 8081
spring:
  # 解决 多个接口上的@FeignClient("相同服务名")会报错,overriding is disabled
  main:
    allow-bean-definition-overriding: true
  # 数据源配置
  datasource:
    # 数据库驱动类名
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接
    url: jdbc:mysql://39.105.58.23/blog?characterEncoding=utf-8&useSSL=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8
    # 数据库用户名
    username: root
    # 数据库访问密码
    password: root.ycw
    # 连接类型
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置
    druid:
      # 初始化大小，最小，最大  
      initial-size: 5
      min-idle: 5
      max-active: 200
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
    cloud:
    # 分布式配置中心
    config:
      # 只有系统环境变量或者系统属性才能覆盖远程配置文件的配置
      override-system-properties: false
        # 缓存
  redis:
    host: 39.105.58.23
    port: 6379
    password: ycw
    #database: 1
    # 是否允许Redis缓存空值
    #cache-null-values: true
    # Redis的键前缀
    #key-prefix: 
    # 缓存超时时间戳,配置为0则不设置超时时间
    #time-to-live: 0ms
    # 是否启用 Redis 的键前缀
    #use-key-prefix: true
    
# pagehelper 配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  
# Mybatis Plus配置
mybatis-plus:
  global-config:
    banner: false
    db-config:
      id-type: auto
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath*:mybatis/mapper/**/*.xml
  configuration:
    # 配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
 
# Feign配置信息
feign:
  client:
    config:
      # 设置全局日志级别
      default:
        # Feign客户端默认的Logger.Level对象定义为NONE级别，不会记录任何Fegin调用过程中的信息
        loggerLevel: full
  # 开启熔断
  hystrix:
    enabled: true
  # 使用 ApacheHttpClient
  httpclient:
    enabled: true 

management:
  endpoints:
    web:
      exposure:
        include: "*" #暴露所有节点
    health:
      sensitive: false #关闭过滤敏感信息
  endpoint:
    health:
      show-details: ALWAYS  #显示详细信息
      
logging:
  level:
    com.ycw: debug
